name: CI
on: [ push, pull_request ]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: clean
        run: make deep_clean

      - name: build
        run: sbt compile

      - name: plugin-test
        run: make test_plugin

      - name: unit-test-coverage
        run: make test_coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
